# Discord settings
discord:
  # Discord webhook URL
  # To create a webhook, see https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks
  # See https://discordapp.com/developers/docs/resources/webhook for more information.
  webhook-url: ''

# Avatar API, for changing the Discord avatar per player
# See https://crafatar.com for details
avatar:
  # craftar.com URL
  url: 'https://crafatar.com/renders/head/'
  # Craftar modifiers/options
  options: 'size=10&overlay'

  # Avatar used for non-chat messages and warnings.
  server-icon: 'https://paradaux.co/hiberniadiscord/default_servericon.png'

# When true, logs some extra output to the console so you can see if/why things might be failing
debug: false

# The following section toggles individual message updates when said events occur.
events:

  # We strongly suggest updating server-icon under the avatar section as this will be the avatar used for these events.
  # If these sections are blank they will be considered disabled. %player% is the only valid placeholder without PlaceholderAPI
  player-join: 'Server Event » %player% has joined the game.'
  player-leave: 'Server Event » %player% has left the game.'


update:
  # Whether or not to automatically check for updates and notify the console if found
  check: true
  # Whether or not to notify players with the hdiscord.admin permission node
  notify: true

# Config version, no touchy plz
version: 2.1